spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
    model:
      chat: openai
      embedding: openai
    retry:
      max-attempts: 3
      on-client-errors: false
      backoff:
        initial-interval: 2s
        multiplier: 2.0
        max-interval: 10s

server:
  port: 8085